subdomain-env: SUBDOMAIN_APP1
static-root: /static/app1

api:
  - context-path: /api
    upstream-env: HOST_APP1
    locations:
      - url: /test1/{id}
        roles: ['TEST_ROLE']
        cache: 10s

  - context-path: /api/auth
    upstream-env: HOST_AUTHAPP
    locations:
      - url: /oauth/token
        security: none
