spring:
  application:
    name: app1
  data:
    mongodb:
      uri: mongodb://localhost/test

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'prometheus'