spring:
  application:
    name: authapp

server:
  port: 9901

application:
  oauth:
    keystore-resource: classpath:jwt.jks
    keystore-password: 123456
    key-alias: jwt
    client-id: browser
    client-secret: $2a$04$ip9jW1YzlabyKxZ3y2vUkO5xxrfh5pscEvIcALF746IzVj/IBWFpy